### ISSUE TITLE
Remain old depth data

### ISSUE THREAD

**Issue by takei0723** [erdewit/ib_insync#270]
At first, thank you for providing this nice library.

I try "reqMktDepth" and check depth, then do "cancelMktDepth".
Later I try again "reqMktDepth" with same conId, then domBids/domAsks include old data, so they have old and new data as double.
Could you please clear old data when "cancelMktDepth"? or please let me know how to do it.

I want to check depth of lots of contracts, but IB accept only 3 depth streaming data, so I request and check and cancel MktDepth on every loop.

Debug code is as follow.

```
from ib_insync import *
# util.startLoop()
from pprint import pprint
#from IPython.display import display, clear_output
import pandas as pd


ib = IB()
ib.connect('127.0.0.1', 7497, clientId=16)

contract = Forex('EURUSD')
ib.qualifyContracts(contract)
ticker = ib.reqMktDepth(contract)


def onTickerUpdate(ticker):
    bids = ticker.domBids
    pprint(bids)
    for i in range(5):
        df.iloc[i, 0] = bids[i].size if i < len(bids) else 0
        df.iloc[i, 1] = bids[i].price if i < len(bids) else 0
    asks = ticker.domAsks
    for i in range(5):
        df.iloc[i, 2] = asks[i].price if i < len(asks) else 0
        df.iloc[i, 3] = asks[i].size if i < len(asks) else 0
    #clear_output(wait=True)
    #display(df)


df = pd.DataFrame(index=range(5),
        columns='bidSize bidPrice askPrice askSize'.split())


ticker.updateEvent += onTickerUpdate

IB.sleep(5)
ib.cancelMktDepth(contract)

IB.sleep(5)
ticker = ib.reqMktDepth(contract)
ticker.updateEvent += onTickerUpdate
IB.sleep(5)

ib.disconnect()
```

**Comment by goodboy** [comment]
@takei0723 the "clearing" of tick data appears to mostly be done in [`Wrapper.tcpDataArrived()`](https://github.com/erdewit/ib_insync/blob/81f9f6c34e6f9632ba1ea16864f6774975986109/ib_insync/wrapper.py#L1048). In theory you could override and modify that method to get what you want in the short term (by clearing `Ticker.domBids` and `Ticker.domAsks` as well).

Imo these fields should be immutable data types since they're always getting overwritten anyway :roll_eyes:. That would have never allowed this problem to happen in the first place. 

Why the DOM is being tracked at this level in the core `Wrapper` at all is also somewhat strange.
Really if you're building a system to track L2 tick data you'd want a proper compact format and the ability to re-construct the DOM from a time range. Checkout [techtonicdb](https://github.com/0b01/tectonicdb) if you'd like something very well built for that purpose.

**Comment by takei0723** [comment]
Thank you for your advice.
But "Wrapper.tcpDataArrived()" cannot clear, the method seems to clear "self.pendingTickers".

I tried to clear "self.tickers" as "self.tickers = {}", then old data can be cleared.
But I am not sure it is proper way or not. How do you think ?

**Comment by erdewit** [comment]
Hi @takei0723,

Thanks for the bug report, the depth data should indeed be cleared on cancelling. The proper place is in ``IB.cancelMktDepth`` and I've added it there.

**Comment by erdewit** [comment]
https://github.com/erdewit/ib_insync/commit/b83d67e552748063288fa06995e72d2a70ae4a66

**Comment by takei0723** [comment]
Hi, @erdewit 
Thank you very much for your prompt action !
