### ISSUE TITLE
Garbage collection of closed subscriptions and tickers

### ISSUE THREAD

**Issue by rgeronimi** [erdewit/ib_insync#338]
It is unclear (based on my limited understanding of the code) if ib_insync is accumulating in various places some data that could be garbage collected instead:
- In various data structures in the wrapper class which has lots of dictionaries to handle pending exchanges with the server
- In other classes (e.g., Ticker. tickByTicks)

My concern for a long-running python process is memory management and more exactly: does the data that has become useless once the calls are completed get garbage collected or not.

Symmetrically, I am wondering what exactly gets accumulated as we go. For example, if I subscribe with a Ticker to market data, does it accumulate historical values (that I don't necessarily require).

PS: if relevant and helpful, I may contribute patches to clean up the places where it unduly accumulates.

**Comment by erdewit** [comment]
The tickers are kept after having been unsubscribed. This is by design - the information may be stale but not necessarily useless. Imho it's not really a practical problem - when I cycled through a literal million tickers the memory consumption was still less than TWS...

Tick data and the results of blocking requests do get cleaned up.
