### ISSUE TITLE
Symbol Name Pending Order

### ISSUE THREAD

**Issue by LinuxpowerLudo** [erdewit/ib_insync#378]
Hi,

First thanks you for great lib !

Can you tell me how i can have the symbol name of my pending orders ? i found reqAllOpenOrders but i don't have symbol name :(

Thanks.
Regards
Ludo.

**Comment by mattsta** [comment]
What you actually want is [`.openTrades()`](https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.openTrades), then you'll get a list of [`Trade` objects](https://ib-insync.readthedocs.io/api.html#ib_insync.order.Trade) which have the contract (with symbol names), order, and order status wrapped together.

**Comment by LinuxpowerLudo** [comment]
Hi matt,
Thanks you for the reply.

I missing something maybe but the .openTrades() get only open trades not pending ?!

For the pending i use reqAllOpenOrders it's ok i see my order but not the symbol name !

[Order(permId=1356751727, action='BUY', totalQuantity=100.0, orderType='MKT', lmtPrice=0.0, auxPrice=0.0, tif='DAY', ocaType=3, rule80A='0', openClose='', eTradeOnly=False, firmQuoteOnly=False, volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='XXXXXXXX', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True)]

**Comment by mattsta** [comment]
Yeah, the name of `.openTrades()` is a little confusing, but it does include all `Pending` or `PreSubmitted` order requests as well. Think of it more as "all live or queued orders submitted to IBKR, but not completed or canceled or expired yet"

There's no need to call `reqAllOpenOrders()` yourself because `ib_insync` keeps the `.openTrades()` result populated with live changes based on real time trade update event callbacks from the IBKR gateway.

There's only three views for activities when using `ib_insync` and they are all maintained live for you:

- all open positions `.positions()` — your entire portfolio of unrealized gains (😁)/losses (😭)
- all open orders not completely filled `.openTrades()` (either live marketable orders waiting at a market/exchange, or simulated/algo orders held at IBKR waiting for triggers)
- all completed trades for the day (cleared every night) as `.fills()` with all completed trade/commission/contract details
  - it's also worth monitoring live executions by their commission updates via the `commissionReportEvent` handler as something like:
```python
self.ib.commissionReportEvent += self.commissionHandler
```

where the handler takes the commission event and runs your "trade completed" logic or logs or outputs real time reports (this example assumes you are running a custom class with custom connected state, because often on connection, the IBKR API will bulk spam recently completed commissions even though they are old):

```python
                    
    def commissionHandler(self, trade, fill, report):
        # Only report commissions if connected (not when loading startup orders)
        if not self.connected:
            logger.warning("Ignoring commission because connection setup not complete...")
            return  
                   
        logger.warning(
            "Order {} commission: {} {} {} at ${} (total {} of {}) (commission ${:,.2f} (${:,.2f} each)){}",
            fill.execution.orderId,
            fill.execution.side,
            fill.execution.shares,
            fill.contract.localSymbol,
            fill.execution.price,
            fill.execution.cumQty,
            trade.order.totalQuantity,
            fill.commissionReport.commission,
            fill.commissionReport.commission / fill.execution.shares,
            f" (pnl {fill.commissionReport.realizedPNL})"
            if fill.commissionReport.realizedPNL
            else "",
        )
```

**Comment by erdewit** [comment]
As mattsta mentioned, ``openTrades()`` contains the orders coupled with the contract info.
