### ISSUE TITLE
Possible to Remove Commissions from avgCost in ib.portfolio()?

### ISSUE THREAD

**Issue by spot92** [erdewit/ib_insync#427]
Is it possible to easily remove the commissions/fees from the avgCost variable in the ib.portfolio()? I would like to perform some calculations on the entry price without these added in. From what I have seen, the best way would be to submit a whatiforder for the contract and then log this into variable and subtract it from the portfolio.avgCost. This seems more complicated than it would need to be. If there is a simpler way, please advise.

Reading through the docs, it does not appear there is an argument I can use to get this returned instead of/in addition to the current avgCost reported.

**Comment by mattsta** [comment]
The math behind `avgCost` handling is standard across the industry because for tax reporting time, they build commissions into your cost basis so you don't have to report hundreds or thousands of commission deductions independently from actual trades.

As for finding actual prices, you can use the commission event or the daily fills data.

You can log actual prices in the commission report using all the values it provides:

https://github.com/mattsta/icli/blob/b01ede3be514994c3ee9ad8dc3221dc0c8503fef/icli/cli.py#L768-L799

You can also (for the same trade day until the ibkr systems reset every night) view your trade execution lots with executed prices and actual commission reporting:

https://github.com/mattsta/icli/blob/b01ede3be514994c3ee9ad8dc3221dc0c8503fef/icli/lang.py#L1762-L1770

**Comment by erdewit** [comment]
The average position cost without commissions is not provided by the API.
