### ISSUE TITLE
Market Data type not modified 

### ISSUE THREAD

**Issue by djangodissilent** [erdewit/ib_insync#439]
Hi erdwit,

I'm trying to request some type 4 tick data from IB using the `ib.reqMarketDataType(4)` function, however, I receive nan values which indicate that IB never sent the data, But when debugging I found out that the market data type is 1!

![image](https://user-images.githubusercontent.com/52085864/153052359-809237d2-aea4-422b-b4b6-1a1c35f6048e.png)
![image](https://user-images.githubusercontent.com/52085864/153052716-f4e9ec05-192e-4601-864d-e64618391e86.png)

Thanks in advance

**Comment by forna** [comment]
I have the same issue. I have set the marketDataType=2 (frozen) to receive the last price also when the market is closed but the result is always nan.  Debugging the code I noticed the marketDataType is actually set to 1.
![image](https://user-images.githubusercontent.com/1431006/161213344-7afa6a65-a73d-4446-aa6e-29a5486f54b2.png)
![image](https://user-images.githubusercontent.com/1431006/161213283-c6eb9e5f-53e5-4a85-92ae-9518063df86b.png)

**Comment by erdewit** [comment]
It turns out that the ``wrapper.marketDataType`` callback can receive a different value than what is specified in the ``ib.reqMarketDataType`` request. This is IBKR's doing so nothing can be done about that on this side.

From experimenting with it, it seems that it's not possible to request delayed data when there's a data subscription for that data.
