### ISSUE TITLE
How to cancel all open orders and close all positions?

### ISSUE THREAD

**Issue by msacs09** [erdewit/ib_insync#468]
Currently I have orders that have OCA trailing stop and take profit for an order attached and at EOD I like to close all my positions. As such below code doesn't exit all positions, they tend to keep the opposite orders open. If I keep them open, in the falling market they r getting triggered and become a working market order. I have to manually cancel those each day.  Can you please advice how we close all positions.
```
def cancel_order(ib, order):
    try:
        ib.cancelOrder(order)
    except Exception as ex:
        print("Unable to cancel the order Reason: {}".format(ex))
    return

 exit_orders = ib.oneCancelsAll([tp_order, sl_order], "OCA_{}".format(str(datetime.now())), 1)
![image](https://user-images.githubusercontent.com/43424222/165184059-5db9ab0d-b077-4606-b71e-25ffb13dbc32.png)

```

**Comment by mattsta** [comment]
For canceling orders, there is a "cancel every open order" single call:

- https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.reqGlobalCancel (also see the upstream docs: https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#a66ad7a4820c5be21ebde521d59a50053)

There isn't a single API call to close out all positions because you need to select closing order types and limit prices per position (but it could be easily automated with the position list and using [midprice](https://interactivebrokers.github.io/tws-api/ibalgos.html#midprice) algo or [adaptive urgent/normal](https://interactivebrokers.github.io/tws-api/ibalgos.html#adaptive) algo close requests per position).

**Comment by msacs09** [comment]
@mattsta thank you. So apparently “ cancelOrder” closes the active positions, but does not close the corresponding OCA bracket order. They keep the trail stop and stop loss order still open ( as u can see in my screenshot) Not sure how do I specify to exit all orders attached to a single order. 

Thx for ur time.

**Comment by erdewit** [comment]
The way that an OCA group works is that a fill (not a cancel) of one order will cancel the other orders.
https://interactivebrokers.github.io/tws-api/oca.html

All open orders are available from ``ib.openTrades()`` and can each be canceled.

Note that ``ib.cancelOrder`` doesn't throw exceptions so an except clause is not necessary.
