### ISSUE TITLE
marketDataType() does not take a value

### ISSUE THREAD

**Issue by baxsmaxbax** [erdewit/ib_insync#517]
After setting the value, reqMktData ignores it.

```
ib.reqMarketDataType(4)
Ticker = ib.reqMktData(con, '', False, False, [])
```

We have in response:
Ticker.marketDataType = 1

**Comment by mattsta** [comment]
yeah, the `reqMarketDataType()` interface is confusing because it does multiple different things depending on the time of day (market open vs. closed):

- it _always_ provides live data if available (1)
- if live data not available, you can enable non-live data results (2, 3, 4), but live data will still be returned if available.


It's explained mostly poorly in the official API docs at:

- https://interactivebrokers.github.io/tws-api/market_data_type.html
- https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#ae03b31bb2702ba519ed63c46455872b6

For my own usage, I set `ib.reqMarketDataType(2)` before my `ib.reqMktData(contract, tickFields)` calls 🤷‍♂️

**Comment by erdewit** [comment]
What is shown by ``ticker.marketDataType`` is what IB is sending back and what is used for the actual market data. As Matt said this can differ from what is requested. It should be possible to get delayed instead of realtime data by using a paper-trading account with a second TWS instance that doesn't have realtime data permissions.
