### ISSUE TITLE
keepUpToDate stops at mid-night

### ISSUE THREAD

**Issue by rsmb7z** [erdewit/ib_insync#533]
Hi @erdewit 
`reqHistoricalData` with `keepUpToDate` being True will stop sending updates at mid-night. Noticed this for consequtive few days. Would be great to have fix.

**Comment by jlixfeld** [comment]
It happens because IBKR resets all client connections and clears the authentication tokens at that time.

The links provided are potentially ways to address that, and there are also others (loosely referred to in the documentation) but they are all outside of the scope of what ib_insync is intended to do.

**Comment by rsmb7z** [comment]
Hi @jlixfeld 
Thanks for help and putting me in right direction.
