### ISSUE TITLE
what is the best way to maintain ib.connect connection to API under same client ID?

### ISSUE THREAD

**Issue by 33327** [erdewit/ib_insync#83]
So what would be the best way of staying connected under the same client ID?
If my system established a connection under client 1 and sent off orders for a symbol A and I continue to monitor under this connection for the status of the orders.

Then in a minute I need to send order for a symbol B, what would I use to check and make sure I currently have an established connection to API under client 1, so that I do not need to create another session with a different client ID to send and monitor my orders?

**Comment by JCepedaVillamayor** [comment]
I think one of the best ways of checking if you're connected to ibc or tws is to use `isConnected` as explained [here](https://rawgit.com/erdewit/ib_insync/master/docs/html/api.html#ib_insync.ib.IB.isConnected)

**Comment by erdewit** [comment]
There are always two connections involved: client to TWS and TWS to IB). For the first one using ib.isConnected() is sufficient. For the second one would have to monitor the error callbacks (like error 1100). Since these errors come with a delay this is not 100% reliable but I would not know anything better.
